name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 
        with:
          ruby-version: '3.1' 
      - name: Install bundler
        run: gem install bundler 
      - name: Install dependencies
        run: bundle install
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Build
        run: |
          npm install
          npm run deploy
